resilience4j:
  circuitbreaker:
    configs:
      myconfig:
        sliding-window-size: 6
        failure-rate-threshold: 50
        wait-duration-in-open-state: 20s
        permitted-number-of-calls-in-half-open-state: 4
        slow-call-rate-threshold: 50
        slow-call-duration-threshold: 2s
    instances:
      products:
        base-config: myconfig
  timelimiter:
    configs:
      myconfig:
        timeout-duration: 6s
    instances:
      products:
        base-config: myconfig

spring:
  cloud:
    gateway:
      routes:
      -  id: products-service
         uri:  lb://products-service
         predicates:           -  Path=/api/products/**
           -  Method=GET, POST
           #-  Header=Content-Type, application/json
         filters:
           -  name: CircuitBreaker
              args:
                name: products
                statusCodes: 500
                #fallbackUri: forward:/api/...           -  StripPrefix=2
           -  name: FilterAddCookie #ExampleGatewayFilterFactory
              args:
                message: Este es un ejemplo de filtro
                cookieName: username
                cookieValue: ElBarto
           
      -  id: items-service
         uri:  lb://items-service
         predicates:
           -  Path=/api/items/**
         filters:
           -  StripPrefix=2  